name = "lintcode"
main = "worker.js"
compatibility_date = "2025-11-25"

[assets]
binding = "ASSETS"
directory = "."
exclude = [
  "**/*.py",
  "todo.md",
  "wrangler.toml",
  "worker.js",
  "package.json",
  "package-lock.json",
  "README.md",
  "**/.git/**"
]
